### ISSUE TITLE
Find () Method in ISuperObject and ISuperArray

### ISSUE THREAD

**Issue by jokorivai** [pult/SuperObject.Delphi#10]
Hi. Thank you for ISuperArray addition, among other things.
Is there any possibility to add Find () Method in both ISuperObject and ISuperArray?
Thank you.

**Comment by pult** [comment]
If you have experience on this topic, you can offer it. I don't have much time at the moment. In the declaration there are search options via path. How do you imagine the declaration and use of Find. Give an example.

**Comment by jokorivai** [comment]
Just got notified a few hours ago. I've updated the library and couldn't found the `Find()` implementation there. I understand, really, if you don't have time for implementing this, and it is OK.

What I meant by `Find()` is like `ISuperArray.Find(SO('{"id": 1, "name": "John Doe"}'))` which will search for item with (or contains) id = 1 and name = "John Doe", if that makes sense.

But thank you anyway for this great library! I'm using it in a couple of my commercial projects.
Also in my trial-and-error project here [https://github.com/AndanTeknomedia/wingp](https://github.com/AndanTeknomedia/wingp)
