### ISSUE TITLE
Undeclared identifier dbg_prefix

### ISSUE THREAD

**Issue by hafedh-trimeche** [pult/SuperObject.Delphi#2]
Hello,

Please note this error:

`[dcc32 Error] superdbg.pas(284): E2003 Undeclared identifier: 'dbg_prefix'`

Best regards.

**Comment by pult** [comment]
dbg_prefix is declared in superobject.pas
but your can uncomment declaration dbg_prefix in superdbg.pas

**Comment by pult** [comment]
your version superobject.pas is "2020.1217.0757" ?

**Comment by hafedh-trimeche** [comment]
Yes

**Comment by pult** [comment]
fixed: https://github.com/pult/SuperObject.Delphi/commit/391528ee388e3a02d0ff257ddc58f98d7fd3d699
