### ISSUE TITLE
Doesn't compile under Delphi 10.2

### ISSUE THREAD

**Issue by vfisher** [pult/SuperObject.Delphi#4]
superobject.pas, line 9928: [dcc32 Error] superobject.pas(9928): E2036 Variable required
>  if CompareMem(@GetTypeData(ATypeInfo).Guid, @soGUID, SizeOf(TGUID)) then

**Comment by pult** [comment]
Fixed at commit https://github.com/pult/SuperObject.Delphi/commit/a50672822d34d5e40ddc6e8886d4a35885e70d8c
